# Copyright (c) 2026 sharonthecreator
# SPDX-License-Identifier: Apache-2.0

manifest:
  version: "1.0"

  defaults:
    remote: zephyrproject-rtos

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
          - littlefs
          - loramac-node
    - name: opus
      url: https://github.com/xiph/opus
      revision: v1.5.2
      path: modules/lib/opus

  self:
    path: modules/zstreamer
