# Copyright (c) 2026 sharonthecreator
# SPDX-License-Identifier: Apache-2.0

CONFIG_LOG=y

# zstreamer framework
CONFIG_ZSTREAMER=y

CONFIG_ZSTREAMER_ADC_SRC=y
CONFIG_ADC=y

CONFIG_ZSTREAMER_DAC_SINK=y
CONFIG_DAC=y
