# Copyright (c) 2026 zstreamer contributors
# SPDX-License-Identifier: Apache-2.0

CONFIG_LOG=y

# zstreamer framework
CONFIG_ZSTREAMER=y
CONFIG_ZSTNODE=y

# ADC source (auto-enabled via DTS)
CONFIG_ADC=y

# Test sink
CONFIG_ZSTNODE_TEST_FAKESINK=y

# Heap memory for ADC DMA buffer allocation (if non-cacheable region not used)
CONFIG_HEAP_MEM_POOL_SIZE=4096
