# Copyright (c) 2026 sharonthecreator
# SPDX-License-Identifier: Apache-2.0

CONFIG_ZSTREAMER=y
CONFIG_ZSTREAMER_TEST_SINE_SRC=y
CONFIG_ZSTREAMER_LORA_SINK=y
CONFIG_ZSTREAMER_PWM_SINK=y
CONFIG_LORA=y
CONFIG_LORA_INIT_PRIORITY=50
CONFIG_PWM=y
CONFIG_LOG=y
